# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59608611a522178ba33e4172f888b63ffed4fe3c82af28077f53b7b79b077484936b7653a9f3f5a7ac7627b340c92dff6cfe09e0bd3ec7a9c4e49f9b75cfd6af

test:
  secret_key_base: ddd7ad51b3adb09ca1bee2ccb741e026180b1c2e36ce9b38f76f731a85f2e9e59cec7b9607f78684cc5d1430793596f71714b4eadb0aa57736b4943ab434431c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
